apiVersion: v1
kind: Secret
metadata:
  name: scheduler-db-credentials
  namespace: cce
  labels:
    app.kubernetes.io/name: cce-scheduler-service
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://postgres.cce.svc.cluster.local:5432/ccedb"
  DB_USERNAME: "scheduler_user"
  DB_PASSWORD: "CHANGE_ME"
